server:
  servlet:
    context-path: /springboot2
spring:
  profiles: 
    active: prod

---
server:
  port: 9991
spring:
  profiles: dev

---
server:
  port: 9992
spring:
  profiles: prod